### ISSUE TITLE
RangeField mutates initial_data

### ISSUE THREAD

**Issue by Rall3n** [Hipo/drf-extra-fields#101]
**Django: v2.2.4**
**DRF Extra Fields: v1.2.4**

Using an instance of the `RangeField` class I could observe that the value of `self.initial_data` inside a serializer has mutated to an empty dict.

```python
// Model
class MyModel(models.Model):
    range = django.contrib.postgres.fields.DecimalField(null=True, blank=True)


// Serializer
class MySerializer(serializers.ModelSerializer):
    range = FloatRangeField()

    class Meta:
        model = MyModel
```

Test setup in `ViewSet.create` method:
```python
serializer = self.get_serializer(data=request.data)

print("Before is_valid: ", request.data.get('range'))
serializer.is_valid(raise_exception=True)
print("After is_valid: ", serializer.initial_data.get('range'))
```

Output:
```
Before is_valid:  {'lower': 22, 'upper': 23, 'bounds': '[]'}
After is_valid:  {}
```

I think the issue is the usage of `(dict).pop` on the `data` argument on [Line 188 in `fields.py`](https://github.com/Hipo/drf-extra-fields/blob/master/drf_extra_fields/fields.py#L188).

A possible workaround for now is to create a new `RangeField` class with the type of `RangeField` you want to use and overwrite the `to_internal_value` method to copy the `data` argument and forward it to the `super().to_internal_value` method:

```python
class CustomFloatRangeField(FloatRangeField):
    def to_internal_value(self, _data):
        if isinstance(_data, dict):
            data = _data.copy()
        else:
            data = _data

        return super().to_internal_value(data)
```

**Comment by alicertel** [comment]
@Rall3n Thank you. I will have a look at this early next week.

**Comment by timur-orudzhov** [comment]
@alicertel do you have any updates about this issue?

**Comment by alicertel** [comment]
@timur-orudzhov I couldn't find time to fix this.  @omerfarukabaci Could you please check this issue when you have time?

**Comment by alicertel** [comment]
This is fixed with the latest release.
