### ISSUE TITLE
proposed new field: BinaryField

### ISSUE THREAD

**Issue by Saida07** [Hipo/drf-extra-fields#102]
Given DRF does not support BinaryField out of the box meanwhile many ask for being able to POST binary data, such as pandas.DataFrame.to_hdf on an external server or a pickled df etc. Its one of the topics it hardly exist any explicit solution to.

Perhaps there is a reason it does not exist, but I am unaware of such reason.

Would be super for everyday programmers to download drf-extra-fields and get an out of the box solution for getting access to BinaryField in a quick uncomplicated manner.

**Comment by yigitguler** [comment]
I am not sure how this can be implemented within the scope of this library. Here is a good discussion about this: https://stackoverflow.com/questions/1509743/what-is-a-good-way-to-transfer-binary-data-to-a-http-rest-api-service

**Comment by alicertel** [comment]
Closed due to lack of response.
