### ISSUE TITLE
500 Error when Base64ImageField is "test" value

### ISSUE THREAD

**Issue by makmary170** [Hipo/drf-extra-fields#109]
Hi!
I use your library to my avatar field, and all work correctly, except i use _"test"_ string as value of avatar field. It have to print 400 Error and Type: _"Please upload a valid image."_, but it show 500 Error and text : _"OSError at /auth/profile/
cannot identify image file <io.BytesIO object at 0x7f85297b3650>"_
May be it does not  understand that  _"test"_ incorrect value of field and then can`t work with it.

**Comment by omerfarukabaci** [comment]
@makmary170 Thank you! I will check this issue as soon as possible.

**Comment by alicertel** [comment]
Hi @makmary170 , this issue fixed with the latest release.

**Comment by makmary170** [comment]
@alicertel Ok, all work, thanks!
