### ISSUE TITLE
RangeField: missed validation of bound ordering

### ISSUE THREAD

**Issue by timur-orudzhov** [Hipo/drf-extra-fields#113]
There is no validation for the case when lower bound is greater than the upper. Django itself check this case in `django.contrib.postgres.forms.ranges.BaseRangeField.compress` method and we should repeat this logic in our corresponding serializer field.

This also leads to the exception – `django.db.utils.DataError: range lower bound must be less than or equal to range upper bound`.

**Comment by timur-orudzhov** [comment]
I see that we've already had pr – #107, which also changes RangeField. I think I can update my pr after merging the former one.

**Comment by alicertel** [comment]
Yes, i merged the Pr. Could you please update your PR?

**Comment by timur-orudzhov** [comment]
Yes, no problem!

**Comment by alicertel** [comment]
Solved with the latest release.
