### ISSUE TITLE
Do you want to welcome RangeFields

### ISSUE THREAD

**Issue by ticosax** [Hipo/drf-extra-fields#12]
https://github.com/tomchristie/django-rest-framework/pull/3632 has been rejected to be into core. I need to find a place to host them. Instead of creating another yet drf third party app, I'm asking if you you are willing to accept the contribution here ?

**Comment by yigitguler** [comment]
We are willing to accept for sure. I understand why they didn't accepted to the core. However i believe that it will be useful for many people. 

Just create a PR. We will handle the rest.

**Comment by auvipy** [comment]
+1

**Comment by ticosax** [comment]
@yigitguler Nice !
I will prepare a pull request.

**Comment by auvipy** [comment]
or could place on drf-extensions!!! tooo

**Comment by ticosax** [comment]
@auvipy thanks for the invite, but too late. I already made the pull request.

Eventually `Hipo/drf-extra-fields` could move entirely to `chibisov/drf-extensions` ?
IMO, It would be nicer if the landscape of drf third party libraries could be consolidated in fewer projects, following an optimistic merging policy[1].

[1] http://hintjens.com/blog:106

**Comment by auvipy** [comment]
that's why I told you for that. In fact most useful drf features should be under an umbrella

**Comment by yigitguler** [comment]
Hi @ticosax,

Thanks for this commit. I merged to master. Tomorrow morning i will prepare version 0.5 and upload to pypi!

**Comment by ticosax** [comment]
@yigitguler 
great news !
thanks

**Comment by yigitguler** [comment]
v 0.5 is released https://pypi.python.org/pypi/django-extra-fields/0.5

**Comment by ticosax** [comment]
:+1:
