### ISSUE TITLE
returned [Object object] in react admin

### ISSUE THREAD

**Issue by thtan89** [Hipo/drf-extra-fields#120]
I have tried the Base64ImageField in Django serializers but in React Admin it returned with [Object object] value. Please rectify the issue. Thank you.

![Screen Shot 2020-02-12 at 12 58 56 PM](https://user-images.githubusercontent.com/51570658/74304385-d0ff1580-4d97-11ea-9187-249c2b668264.png)

The example code in Django serializers:

```
class UploadedBase64ImageSerializer(serializers.Serializer):
    attachment = Base64ImageField(required=False)
        
class WorkRequestTestSerializer(serializers.ModelSerializer):
    WRNO = serializers.CharField(read_only=True)
    attachment = 'R0lGODlhAQABAIAAAAAAAP///yH5BAEAAAAALAAAAAABAAEAAAIBRAA7'
    attachment = UploadedBase64ImageSerializer(data={'attachment': attachment})
```

I use ImageInput in React Admin:

```
<ImageInput source="attachment" label="Attachment" accept="image/*">
   <ImageField source="src" title="title" />
</ImageInput>
```

**Comment by alicertel** [comment]
Hi @thtan89, Are you still having the issue?
