### ISSUE TITLE
Support for ListField(child=Base64ImageField())

### ISSUE THREAD

**Issue by johnthagen** [Hipo/drf-extra-fields#122]
We would like to support uploading multiple base64 encoded files to a single PostgreSQL `ArrayField`. Is `ListField(child=Base64ImageField())` supported?

Skeleton example:

```py
# models.py
from django.contrib.postgres.fields import ArrayField

class Store(Model):
    files = ArrayField(models.FileField(upload_to='files', null=True, blank=True))
```

```py
# serializers.py
from drf_extra_fields.fields import Base64ImageField
from rest_framework.fields import ListField

class StoreSerializer(ModelSerializer):
    datasheets = ListField(child=Base64ImageField())

    class Meta:
        model = Store
        fields = '__all__'
```

```py
# views.py
class StoreViewSet(ModelViewSet):
    queryset = Store.objects.all()
    serializer_class = StoreSerializer
```

When I POST something like:

```json
{
    "files": ["<B64_FILE>"]
}
```

The response I see in the debugger when testing in `pytest` from the POST (and subsequent GETs) looks like:

```py
{
    "files": [None]
}
```

No files seem to be stored either.

Before investigating this further, I wanted to check if this was something that was officially supported or if there was some reason that `Base64ImageField` wouldn't be compatible with `ListField`?

**Comment by johnthagen** [comment]
Even more interesting is that when I fetch the endpoint with another `Serializer` set up using `represent_in_base64=True`:

```py
class StoreSerializer(ModelSerializer):
    files = ListField(child=Base64FileField(represent_in_base64=True))

    class Meta:
        model = Store
        fields = '__all__'
```

```py
{
    "files": ["Raw content"]
}
```

**Comment by johnthagen** [comment]
Potential related upstream Django issue: https://code.djangoproject.com/ticket/25756

**Comment by johnthagen** [comment]
Since this is actually an upstream Django problem (https://code.djangoproject.com/ticket/25756), I will close this issue.

**Comment by alicertel** [comment]
Thank you @johnthagen
