### ISSUE TITLE
Drop support for django 1.x and python 2.7

### ISSUE THREAD

**Issue by alicertel** [Hipo/drf-extra-fields#124]

**Comment by johnthagen** [comment]
Can also drop support for Python 2.7, which is end of life and neither Django nor DRF support any longer.

**Comment by alicertel** [comment]
Sure, updated the issue.

**Comment by ulgens** [comment]
@alicertel Any update on this? I can take the issue.

**Comment by alicertel** [comment]
@ulgens That would be great. Thank you :)
