### ISSUE TITLE
Support for djangorestframework-recursive

### ISSUE THREAD

**Issue by joshcorne** [Hipo/drf-extra-fields#128]
Hey, 

There doesn't seem to be a way to set the presentation_serializer as itself. My model allows a foreign key to the same model. Is there a way to integrate with djangorestframework-recursive?

Thanks!

**Comment by yigitguler** [comment]
Hi,

Could you please give more details? Which field you mean?

**Comment by joshcorne** [comment]
Hi, sorry for the lack of details.

My model is:
```
class Project(models.Model):
    linkedProject = models.ForeignKey("self",null=True,blank=True,on_delete=models.PROTECT)
```

And this is how I would like to be able to serialize it:

```
class ProjectSerializer(serializers.ModelSerializer):
    linkedProject = PresentablePrimaryKeyRelatedField(
        queryset=Project.objects.all(),
        presentation_serializer="self",
        allow_null=True,
        required=False
    )
```
But unfortunately this doesn't appear to be possible, to have a serializer reference itself.
If I didn't want it to be a PresentablePrimaryKeyRelatedField then I could use djangorestframework-recursive but then obviously when I POST, it expects a dict as opposed to the PK.
```
class ProjectSerializer(serializers.ModelSerializer):
    linkedProject = RecursiveField()
```

My current solution is to create another serializer for the same model (minus most of the fields) and link to that:

```
class LinkedProjectSerializer(serializers.ModelSerializer):
    class Meta:
        model = Project
        fields = ('id','serial','customerName')

class ProjectSerializer(serializers.ModelSerializer):
    linkedProject = PresentablePrimaryKeyRelatedField(
        queryset=Project.objects.all(),
        presentation_serializer=LinkedProjectSerializer,
        allow_null=True,
        required=False
    )
```

I wondered if there was any way to manage this without the need for another serializer. The current solution I have works and I'm happy with if it has to be that way though.

Thanks a lot :)

**Comment by yigitguler** [comment]
Thank you for the detailed explanation. We will check and get back to you.

**Comment by alicertel** [comment]
I will try do add support for "self" next week.

**Comment by alicertel** [comment]
presentation_serializer accepts string path of the serializer class. For example: app.serializers.RepresentationSerializer
