### ISSUE TITLE
Upload wheels to PyPI

### ISSUE THREAD

**Issue by johnthagen** [Hipo/drf-extra-fields#130]
Wheels (`.whl`) for this package are currently missing from PyPI. Could wheels be uploaded for the current and future releases?

Read more about the [advantages of wheels](https://pythonwheels.com/) to understand why generating wheel distributions are important.

To create a wheel along with source distribution:

```bash
(venv) $ pip install --upgrade pip setuptools wheel
(venv) $ python setup.py sdist bdist_wheel

# See dist/*.whl
```

To upload wheels:

```bash
(venv) $ pip install twine
(venv) $ twine upload dist/*
````

**Comment by johnthagen** [comment]
@alicertel Any chance this issue could be picked up?

**Comment by alicertel** [comment]
Sure. I will have a look at this for the next release. Thank you @johnthagen

**Comment by alicertel** [comment]
Hi @johnthagen . I uploaded *.whl to pypi for the latest release and will upload for future releases as well. Thank you for the contribution.

**Comment by johnthagen** [comment]
Great! Thank you!

**Comment by johnthagen** [comment]
Confirmed that wheels are used when pip installing the latest version:

```
pip install django-extra-fields
Collecting django-extra-fields
  Downloading django_extra_fields-3.0.0-py3-none-any.whl (15 kB)
...
```
