### ISSUE TITLE
Base64 Image Downloads

### ISSUE THREAD

**Issue by terfn** [Hipo/drf-extra-fields#14]
I’m working on a drf API where I have an ImageField in a model and I added a field for base64 downloads to a serializer, which basically consists of opening the image file and encoding it in ```to_representation```. Seems like that would be a nice addition to your Base64ImageField. Shall I make a PR adding this?

**Comment by yigitguler** [comment]
Hi Filip,

Generally we are using this field to **upload** images in base 64 format and serving as a URL. However, your addition can also be nice. 

If you can make this feature optional (default=False), then we will be happy to merge.

For example, while defining the field, if the developer adds something like `represent_in_base64=True`, then it can display the base64 output as well.

**Comment by terfn** [comment]
Ok I'll look into it. Thanks for letting me know.
