### ISSUE TITLE
DateRangeField empty value validation

### ISSUE THREAD

**Issue by AtalayBaysal** [Hipo/drf-extra-fields#141]
My serializer is below;

```

class MuseumClosedSerializer(serializers.ModelSerializer):
    dates = DateRangeField(label=_("Between dates"))

    class Meta:
        model = models.MuseumClosed
        fields = ("id", "museum", "dates")

```

My problem is if dates data send as empty (such as "[)"), serializer accept it instead of return validation error. Is there any way i can use?

**Comment by alicertel** [comment]
@AtalayBaysal Thanks for reporting this issue. Are you using latest version of the package? If so could you please provide the exact data/input?

**Comment by AtalayBaysal** [comment]
@alicertel thanks for quick response, here is my package versions;
```
Python 3.8.2
django-extra-fields==2.0.5
Django==3.0.9
djangorestframework==3.11.0
```
Requested data:
```
{
    "museum": 1,
    "dates": {}
}
```
Response:
```
{
    "id": 2,
    "museum": 1,
    "dates": {
        "lower": null,
        "upper": null,
        "bounds": "[)"
    }
}
```

**Comment by alicertel** [comment]
@AtalayBaysal Thank you for the details. I will work on this and let you know once it's fixed.

**Comment by alicertel** [comment]
@AtalayBaysal allow_empty, True by default, attribute is added to DateRangeField.
Sample usage:
`dates = DateRangeField(allow_empty=False)`

**Comment by AtalayBaysal** [comment]
Thanks for the fix, seems work properly now :+1: .
