### ISSUE TITLE
Unlisted dependancy psycopg2

### ISSUE THREAD

**Issue by todorvelichkov** [Hipo/drf-extra-fields#142]
Trying to use `drf-extra-fields` after being installed with just `pip install drf-extra-fields` fails because `psycopg2` in not listed in `requirements.txt` (`psycopg2` is used as an import in your `fields.py` file). After manually installing `psycopg2` from pip it all works fine.

**Comment by alicertel** [comment]
You need to install psycopg2 manually to be able to use postgres with Django. We can follow the same approach in this package but we have a strict dependency to psycopg2 in fields.py. It works just fine if you are using postgress.

I believe right approach would be to remove `psycopg2` dependency from code and make the depended fields optional.  So if psycopg2 is installed (you have to install this to be able to use postgres with django) these fields will be available to use.

**Comment by ulgens** [comment]
I think the best option here is adding psycopg2 as optional dependancy and use it like `pip install drf-extra-fields[postgres]`. I can take the issue if that's okay.

**Comment by alicertel** [comment]
@ulgens That would be great.

But the thing is the psycopg2 is not optional at the moment. It should also be optional in the code level.

**Comment by lmbringas** [comment]
Hello everyone, how can i do if i don't use postgres as my db ? do i need to install psycopg2 ?

**Comment by alicertel** [comment]
@lmbringas Right now yes the code depends on the `psycopg2`.

@ulgens will work on this to make it optional for non postgres users. @ulgens are you available these days? If not please let me know i can work on this.

**Comment by lmbringas** [comment]
there is something i can do ? maybe i can help. if you put some try catch on import and then set a flag on catch to not map the field, it will work ?

**Comment by todorvelichkov** [comment]
I guess you can take a look how [django-mysql](https://github.com/adamchainz/django-mysql) has done something similar for their [DynamicField](https://github.com/adamchainz/django-mysql/blob/master/src/django_mysql/models/fields/dynamic.py#L27) field which depends on `mariadb_dyncol`. For the purpose they used the [check](https://docs.djangoproject.com/en/3.1/topics/checks/#field-model-manager-and-database-checks) method of the field.

**Comment by ulgens** [comment]
Taking this today, sorry for the delay.

**Comment by lmbringas** [comment]
Thank you @todorvelichkov for the documentation. There is no problem by delay @ulgens. I've already get the solution. Maybe this could works for everyone, check [pull requests 145](https://github.com/Hipo/drf-extra-fields/pull/145)

**Comment by danaki** [comment]
Is it tightly bound to postgres? I'm just developing locally using sqlite database and getting "psycopg2 not found" error.
Please move all the code related to postgres into a separate module so that people using other database engines could use this package for their purposes.

**Comment by lmbringas** [comment]
hey @danaki  you should check this pull requests https://github.com/Hipo/drf-extra-fields/pull/145, i think i can help to you. I'm using it in production without psycopg2.

**Comment by Capit0L** [comment]
I think this issue is important. 
I'm not using PostgreSQL in both dev and production environments. But it requires to install psycopg2. On top of that I have to install PostgreSQL Client on dev/production server.

**Comment by alicertel** [comment]
Agreed, there is an active PR to fix the issue.

**Comment by gabn88** [comment]
Any timeline for the PR to get merged?

**Comment by alicertel** [comment]
@gabn88  I've merged the PR to master. I will try this on one of our active projects and take a new release later next week if everything goes well.

**Comment by aivazoff** [comment]
> @ulgens Это было бы здорово.
> 
> Но дело в том, что psycopg2 на данный момент не является обязательным. Он также должен быть необязательным на уровне кода.

Hello, 
please update this package at pypi.org
