### ISSUE TITLE
Wrong order of latitude/longitude.

### ISSUE THREAD

**Issue by 0legRadchenko** [Hipo/drf-extra-fields#143]
Guys, could you please fix this asap.
Data I send:
{
    "location": {"longitude": 38, "latitude": 45}
}
Data I return back from DB from json:
'{ "type": "Point", "coordinates": [ 38.975348, 45.037295 ] }'
The order changes and it depicts as latitude 38 and longitude 45
I did manage to get to know how to fix this. By changing these lines:
'POINT(%(latitude)s %(longitude)s)'
            value = {
                "latitude": value.x,
                "longitude": value.y
            }
But I cant use it in production... Could you please solve this issue?

**Comment by yigitguler** [comment]
Hi,

Nothing is wrong here. X is always longitude and Y is always latitude.

{ "type": "Point", "coordinates": [ 38.975348, 45.037295 ] }

In this case, the longitude is 38 and the latitude is 45.
