### ISSUE TITLE
Range field default display value error

### ISSUE THREAD

**Issue by AtalayBaysal** [Hipo/drf-extra-fields#146]
There is an issue using version 3.x.x and rest framework interface. If model serializer contains DateRangeField server raise 500 error as "_'dict' object has no attribute 'isempty'_" on drf_extra_fields/fields.py in to_representation, line 224

Some how value parameter expected object but get as empty dictionary.

**Comment by alicertel** [comment]
@AtalayBaysal I will look into the issue this week.

**Comment by gwtwod** [comment]
Some extra details in case it helps:

I get the same error in the DRF browsable API while listing all objects, but not when I view single objects (tried all of them individually). I also use `drf-yasg` where listing and single objects work fine.

`period = DateTimeRangeField(allow_empty=True)`

Using
```
django-extra-fields==3.0.2
Django==3.1.2
djangorestframework==3.12.1```

**Comment by alicertel** [comment]
Opened a pr for the issue https://github.com/Hipo/drf-extra-fields/pull/148 Will take a release later next week.

**Comment by AtalayBaysal** [comment]
Hi @alicertel,
 when will you merge #148 ?

**Comment by alicertel** [comment]
Hi @AtalayBaysal I will take a new release on monday.

**Comment by alicertel** [comment]
It's merged to master.

**Comment by alicertel** [comment]
@AtalayBaysal It's released.
