### ISSUE TITLE
'dict' object has no attribute 'isempty'

### ISSUE THREAD

**Issue by vkhansen** [Hipo/drf-extra-fields#147]
Hello I am seeking assistance with this error, I can view my individual model instances by primary key, but cannot view the list.

`from rest_framework import viewsets

from major.apps.common.views import ActionRelatedSerializerMixin
from major.apps.master_data.job_grades.models import JobGrade
from major.apps.master_data.job_grades.serializers import JobGradeSerializer, JobGradeListSerializer

class JobGradeViewSet(ActionRelatedSerializerMixin, viewsets.ModelViewSet):
    queryset = JobGrade.objects.all()
    list_serializer_class = JobGradeListSerializer
    write_serializer_class = JobGradeSerializer
    retrieve_serializer_class = JobGradeSerializer`

`from model_controller.serializers import ModelControllerSerializer
from rest_framework.serializers import ModelSerializer
from major.apps.master_data.job_grades.models import JobGrade
from drf_extra_fields.fields import IntegerRangeField

class JobGradeSerializer(ModelSerializer):
    grade = IntegerRangeField()

    class Meta:
        model = JobGrade
        fields = ('id', 'grade_name', 'grade', 'color')

class JobGradeListSerializer(ModelControllerSerializer):

    class Meta:
        model = JobGrade
        fields = ('id', 'grade_name', 'color')`

`from django.db import models
from colorfield.fields import ColorField
from django.contrib.postgres.fields import IntegerRangeField

class JobGrade(models.Model):
    grade_name = models.CharField(max_length=255, db_index=True)
    color = ColorField(default='#FF0000', blank=True)
    grade = IntegerRangeField(db_index=True)

    class Meta:
        ordering = ('pk',)

    def __str__(self):
        return self.grade_name`

`Environment:

Request Method: GET
Request URL: http://127.0.0.1:8000/api/masterdata/job-grades/

Django Version: 3.1.2
Python Version: 3.8.6
Installed Applications:
['django.contrib.admin',
 'django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.messages',
 'django.contrib.staticfiles',
 'django.contrib.humanize',
 'major.apps.acknowledgments.apps.AcknowledgmentsConfig',
 'major.apps.authentication.apps.AuthenticationConfig',
 'major.apps.budgets.apps.BudgetsConfig',
 'major.apps.claims.apps.ClaimsConfig',
 'major.apps.common.apps.CommonConfig',
 'major.apps.companies.apps.CompaniesConfig',
 'major.apps.data_migrations.apps.DataMigrationsConfig',
 'major.apps.data_importations.apps.DataImportationsConfig',
 'major.apps.departments.apps.DepartmentsConfig',
 'major.apps.estaff.apps.EstaffConfig',
 'major.apps.general_memos.apps.GeneralMemosConfig',
 'major.apps.job_positions.apps.JobPositionsConfig',
 'major.apps.level_of_approvals.apps.LevelOfApprovalsConfig',
 'major.apps.master_data.job_grades.apps.JobGradesConfig',
 'major.apps.master_data.projects.apps.ProjectsConfig',
 'major.apps.master_data.pr_items.apps.PrItemsConfig',
 'major.apps.master_data.symptoms.apps.SymptomsConfig',
 'major.apps.master_data.vendors.apps.VendorsConfig',
 'major.apps.master_data.welfares.apps.WelfaresConfig',
 'major.apps.master_data.memo_cc_groups.apps.MemoCcGroupsConfig',
 'major.apps.memos.apps.MemosConfig',
 'major.apps.my_tasks.apps.MyTasksConfig',
 'major.apps.news_feed.apps.NewsFeedConfig',
 'major.apps.notifications.base.apps.BaseNotificationsConfig',
 'major.apps.notifications.email.apps.EmailNotificationsConfig',
 'major.apps.notifications.line.apps.LineNotificationsConfig',
 'major.apps.notifications.website.apps.WebsiteNotificationsConfig',
 'major.apps.operation_logs.apps.OperationLogsConfig',
 'major.apps.people.apps.PeopleConfig',
 'major.apps.purchase_requisitions.apps.PurchaseRequisitionsConfig',
 'major.apps.service_requests.apps.ServiceRequestsConfig',
 'computedfields.apps.ComputedfieldsConfig',
 'corsheaders',
 'django_auth_adfs',
 'django_cleanup',
 'django_extensions',
 'django_filters',
 'colorfield',
 'drf_extra_fields',
 'minio_storage.apps.DjangoStoragesConfig',
 'rest_framework.apps.RestFrameworkConfig',
 'sequences.apps.SequencesConfig',
 'debug_toolbar.apps.DebugToolbarConfig',
 'silk']
Installed Middleware:
['django.middleware.security.SecurityMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'corsheaders.middleware.CorsMiddleware',
 'django.middleware.locale.LocaleMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware',
 'debug_toolbar.middleware.DebugToolbarMiddleware',
 'silk.middleware.SilkyMiddleware']

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/asgiref/sync.py", line 330, in thread_handler
    raise exc_info[1]
  File "/usr/local/lib/python3.8/site-packages/django/core/handlers/exception.py", line 38, in inner
    response = await get_response(request)
  File "/usr/local/lib/python3.8/site-packages/django/core/handlers/base.py", line 261, in _get_response_async
    response = await sync_to_async(response.render, thread_sensitive=True)()
  File "/usr/local/lib/python3.8/site-packages/asgiref/sync.py", line 296, in __call__
    ret = await asyncio.wait_for(future, timeout=None)
  File "/usr/local/lib/python3.8/asyncio/tasks.py", line 455, in wait_for
    return await fut
  File "/usr/local/lib/python3.8/site-packages/asgiref/current_thread_executor.py", line 23, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.8/site-packages/asgiref/sync.py", line 334, in thread_handler
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/template/response.py", line 105, in render
    self.content = self.rendered_content
  File "/usr/local/lib/python3.8/site-packages/rest_framework/response.py", line 70, in rendered_content
    ret = renderer.render(self.data, accepted_media_type, context)
  File "/usr/local/lib/python3.8/site-packages/rest_framework/renderers.py", line 724, in render
    context = self.get_context(data, accepted_media_type, renderer_context)
  File "/usr/local/lib/python3.8/site-packages/rest_framework/renderers.py", line 655, in get_context
    raw_data_post_form = self.get_raw_data_form(data, view, 'POST', request)
  File "/usr/local/lib/python3.8/site-packages/rest_framework/renderers.py", line 563, in get_raw_data_form
    data = serializer.data.copy()
  File "/usr/local/lib/python3.8/site-packages/rest_framework/serializers.py", line 548, in data
    ret = super().data
  File "/usr/local/lib/python3.8/site-packages/rest_framework/serializers.py", line 250, in data
    self._data = self.get_initial()
  File "/usr/local/lib/python3.8/site-packages/rest_framework/serializers.py", line 396, in get_initial
    return OrderedDict([
  File "/usr/local/lib/python3.8/site-packages/rest_framework/serializers.py", line 397, in <listcomp>
    (field.field_name, field.get_initial())
  File "/usr/local/lib/python3.8/site-packages/drf_extra_fields/fields.py", line 234, in get_initial
    return self.to_representation(initial)
  File "/usr/local/lib/python3.8/site-packages/drf_extra_fields/fields.py", line 224, in to_representation
    if value.isempty:

Exception Type: AttributeError at /api/masterdata/job-grades/
Exception Value: 'dict' object has no attribute 'isempty'
`

**Comment by vkhansen** [comment]
the error relates to this part:

`    def to_representation(self, value):
        """
        Range instances -> dicts of primitive datatypes.
        """
        if value.isempty:
            return {'empty': True}
        lower = self.child.to_representation(value.lower) if value.lower is not None else None
        upper = self.child.to_representation(value.upper) if value.upper is not None else None
        return {'lower': lower,
                'upper': upper,
                'bounds': value._bounds}`

**Comment by alicertel** [comment]
Hey @vkhansen  Thanks for the issue, I've opened a PR https://github.com/Hipo/drf-extra-fields/issues/147 for this.
