### ISSUE TITLE
How to set field as nullable?

### ISSUE THREAD

**Issue by TJHeeringa** [Hipo/drf-extra-fields#150]
I have a `Student` model with a relation to `Study`. This relation can be set to `null`, however when using the `PresentableRelatedFieldMixin` I cannot get it to work. It keeps saying `study is required`. 

A minimal reproducing example should be something like

### Fields
```python
class PresentableHyperlinkedRelatedField(PresentableRelatedFieldMixin, HyperlinkedRelatedField):
    pass
```

### Models
```python
class Student(models.Model):
    slug = models.SlugField(default=uuid.uuid4, editable=False)
    study = models.ForeignKey('Study', related_name='student', on_delete=models.PROTECT, null=True, blank=True)

class Study(models.Model):
    slug = models.SlugField(default=uuid.uuid4, editable=False)
```

### Serializers
```python
class StudySerializer(serializers.Serializer):
    class Meta:
        model = Study
        fields = ('slug', )
        extra_kwargs = {
            'url': {'lookup_field': 'slug'},
        }

class StudentSerializer(serializers.Serializer):
    study = PresentableHyperlinkedRelatedField(lookup_field='slug', presentation_serializer=StudySerializer,
                                               presentation_serializer_kwargs={'nested': True}, required=False,
                                               view_name='study-detail', queryset=Study.objects.all())
    class Meta:
        model = Student
        fields = ('slug', 'study')
        extra_kwargs = {
            'url': {'lookup_field': 'slug'},
        }
```
to which I give the data in my tests like

```python
data = {"study": null}
response = self.client.patch("/student/<slug>", data=data)
self.assertEqual(200, response.status_code, "Error: {}".format(response.data))
```
When using the `HyperlinkedRelatedField` directly it works, but when I replaced the `HyperlinkedRelatedField` with the `PresentableHyperlinkedRelatedField` I got the error `study is required`. Any clue why this would happen?

**Comment by alicertel** [comment]
Hi @TJHeeringa, It's strange that it's working with `HyperlinkedRelatedField` as expected but not with PresentableHyperlinkedRelatedField since this field only overrides the representation data. 

I will investigate the issue and get back to you.

**Comment by alicertel** [comment]
@TJHeeringa Could you please try with `allow_null=True`?

**Comment by TJHeeringa** [comment]
Adding the `allow_null=True` resolved the issue. Thx!
