### ISSUE TITLE
Rendering DecimalRangeField as a list

### ISSUE THREAD

**Issue by robvdl** [Hipo/drf-extra-fields#152]
I'm just wondering why DecimalRangeField renders like this, it seems a bit overengineered:

    "weight_range": {"lower": "50.`1", "upper": "200.34", "bounds": "[)"},

Personally I would have just rendered it like this:

    "weight_range": ["50.12", "200.34"]

Also I have made a custom DecimalField model field and Django form field that allows max_digits and decimal_places to be set as that really bugged me in Django that the regular Decimal field has this but DecimalRangeField does not. In this library max_digits and decimal_places cannot be set either, they are hard-coded to None. I was hoping to be able to use this library, but I might have to write my own field that renders to a much simpler list.

**Comment by robvdl** [comment]
I guess because it is possible that the upper or lower bound isn't set unless `require_all_fields=True`

**Comment by alicertel** [comment]
`"weight_range": ["50.12", "200.34"]` I can't understand if the range includes the value "50.12" or "200.34". `bounds` (`[)`) gives this info. Which means weight can be 50.12 but cannot be 200.34.
