### ISSUE TITLE
Allow passing None to lower/upper of RangeField

### ISSUE THREAD

**Issue by michaelhays** [Hipo/drf-extra-fields#153]
Take this simple serializer:

```py
class SimpleSerializer(serializers.Serializer):
    integer_range = IntegerRangeField()

    class Meta:
        fields = ["integer_range"]
```

Passing data with just one of `lower`/`upper` succeeds, creating a range that is unbounded in the opposite direction:

```py
serializer = SimpleSerializer(data={
    "integer_range": {
        "lower": 0,
    },
})

serializer.is_valid()
# True

serializer.validated_data
# OrderedDict([('integer_range', NumericRange(0, None, '[)'))])
```

However, passing a value of `None` for the other direction fails:

```py
serializer = SimpleSerializer(data={
    "integer_range": {
        "lower": 0,
        "upper": None,
    },
})

serializer.is_valid()
# False

serializer.errors
# {'integer_range': [ErrorDetail(string='This field may not be null.', code='null')]}
```

This is because `RangeField.to_internal_value` [validates `upper`](https://github.com/Hipo/drf-extra-fields/blob/c010ea06fed9dbcb51a93a1761dae7eef49357d2/drf_extra_fields/fields.py#L217) using the child class (in this case, `IntegerField`) as long as the key exists in the incoming dictionary. The end user of `drf-extra-fields` has no control over how the range child class is [instantiated](https://github.com/Hipo/drf-extra-fields/blob/c010ea06fed9dbcb51a93a1761dae7eef49357d2/drf_extra_fields/fields.py#L261), so this fails when `upper` is equal to `None` since the child class is called without `allow_null=True`.

Is there any way we can add the ability to pass `None` to `lower`/`upper` in the data here? We'd likely need to add new arguments (`allow_lower_null`/`allow_upper_null`, perhaps) in order to keep things backwards-compatible. Though maybe there's a better solution that I'm not thinking of.

### EDIT

On second thought, I don't love the `allow_lower_null`/`allow_upper_null` solution for a couple of reasons:

1. It diverges from the Django range fields, which as I understand, always allow the lower and upper bounds to be empty, and
2. The `drf-extra-fields` `RangeField`s are currently non-reflexive; that is, it's possible that the data from a valid serialized representation can't be used as deserialization data:

```py
serializer = SimpleSerializer(data={
    "integer_range": {
        "lower": 0,
     },
})

serializer.is_valid()
# True

serializer.data
# {'integer_range': {'lower': 0, 'upper': None, 'bounds': '[)'}}

second_serializer = SimpleSerializer(data=serializer.data)

second_serializer.is_valid()
# False

second_serializer.errors
# {'integer_range': [ErrorDetail(string='This field may not be null.', code='null')]}
```

This seems broken to me, to the point where a backwards-incompatible change would be worth the fix. Especially one that I can't imagine would break many existing projects using these fields, if any.

**Comment by alicertel** [comment]
@michaelhays Thank you for the detailed explanation. I agree that we should have more room to customize the behaviour of the child field.

How about adding child_attrs attribute to the RangeField to define behaviours of the child field? That way allowing null or not can be customizable. This would also be backward compatible.

Sample usage: `IntegerRangeField(child_attrs={"allow_null":True, "validators":,....} )`

What do you think?

**Comment by michaelhays** [comment]
That makes sense to me! Maybe in the future it would make sense to have `"allow_null": True` as the default for the child class, like for the 4.0 release. But I understand why you wouldn't want to do that now.

Would you like me to take a crack at that change or are you planning to?

**Comment by alicertel** [comment]
Yes, there are many users of this package. It's best we handle this without breaking things.

I would appreciate if you can open a PR for this.
