### ISSUE TITLE
requiring DateRangeField

### ISSUE THREAD

**Issue by dbinetti** [Hipo/drf-extra-fields#16]
When I try to PUT a model with a DateRangeField it returns "this field is required", even when the model is null=True, blank=True.  Any pointers on how to debug/confirm?

**Comment by yigitguler** [comment]
@ticosax is the author of these fields. Pinging him.

**Comment by ticosax** [comment]
@dbinetti did you specified a `default` ?

**Comment by dbinetti** [comment]
no, i did not -- but i am not expecting to given the null=True, blank=True.

**Comment by lambdacomplete** [comment]
@dbinetti when using PUT (replace, unlike PATCH which is partial update) you should give all non-read-only fields specified in the serializer, might it be that you put the `DateRangeField` among the `fields` there?

**Comment by dbinetti** [comment]
Thanks for the responses.  I've done a few things and am getting closer (i think?), but still can't get it to work.

I am now trying to POST (create) a model that includes a null DateRangeField.  The field is nullable.  It is responding with a 400 and "This field may not be null."  Also please note that I am using a JSON API adapter.

**Comment by ticosax** [comment]
`RangeField`s doesn't take any decision regarding `null`, `required`, `blank` or `default` or whatever options Fields accept. All this validation happen in DRF. You will have to dig into its documentation to sort things out.

**Comment by dbinetti** [comment]
OK, basic facepalm  here.  The `null` that DRF expects is an empty dictionary, not `null` itself.  Thanks for pointing me in the right direction.

**Comment by dbinetti** [comment]
OK, reopening this.  Might still be a DRF issue, but not sure.  Here is a repo that has a failing test.  Please let me know if I this is a bug, if I should open an issue on DRF, or am misusing the field.

https://github.com/dbinetti/djangodaterange

**Comment by ticosax** [comment]
Since `RangeField` inherit from from `rest_framework.fields.DictField`.
Can you isolate the unexpected behavior to `RangeField` only and not `DictField` ?
If no, it means you gonna have to ask on DRF mailing list. Because this is how `DictField` is behaving.

FYI, I'm using `(default=None, blank=True, null=True)` in my model's field definition.

**Comment by dbinetti** [comment]
You're right -- this is disallowed by `DictField`.  Asking on DRF.  I think I may be using the `RangeField` inappropriately, but not sure
