### ISSUE TITLE
3.2.0 not published to pypi

### ISSUE THREAD

**Issue by pegler** [Hipo/drf-extra-fields#166]
Though v3.2.0 just got tagged today, it's not on pypi yet. Thanks for maintaining this package!

**Comment by yigitguler** [comment]
Thank you for reporting this.

**Comment by omerfarukabaci** [comment]
@pegler Thanks a lot for the issue! 🚀  We have realized an error in the version `3.2.0` which prevents installing the package for Python 3.6, so we have released a new version and published it instead:

https://pypi.org/project/drf-extra-fields/
