### ISSUE TITLE
v3.3.0 not released in PyPI

### ISSUE THREAD

**Issue by iflare3g** [Hipo/drf-extra-fields#174]
Based on the README on master branch and Git's tags, the latest version is the v3.3.0 that drops the py 36 support.
But the 3.3.0 hasn't been published to PyPI.

Is there the possibility to kindly publish it, please ? 

Thanks so much for your effort on this project!

**Comment by omerfarukabaci** [comment]
Thanks for your kind words! Sorry about that, just published 3.3.0 to PyPI:

https://pypi.org/project/drf-extra-fields/3.3.0/

**Comment by iflare3g** [comment]
thanks so much!
