### ISSUE TITLE
`Pillow` should be listed as a dependency

### ISSUE THREAD

**Issue by beltekylevi** [Hipo/drf-extra-fields#182]
When `drf-extra-fields` is installed with Poetry `Pillow` is not installed hence you cannot properly use `Base64ImageField`.

https://github.com/Hipo/drf-extra-fields/blob/3dbb40b5b617926d8a3ab481f6e53cd84a9ff38b/drf_extra_fields/fields.py#L136-L140

Am I doing something wrong or `Pillow` should be listed in the `requirements.txt`?

**Comment by KaratasFurkan** [comment]
You were right, `Pillow` was intended to be a non-mandatory improvement/fallback but the implementation was otherwise. We refactored it and it's now a "hidden" fallback.

**Comment by beltekylevi** [comment]
Thank you!
