### ISSUE TITLE
Allow WebP format for Base64ImageField

### ISSUE THREAD

**Issue by dfg-98** [Hipo/drf-extra-fields#183]
## Feature Request:

Allow [WebP](https://developers.google.com/speed/webp) format in Base64ImageField

## Current Behavior:

When trying to upload a base64 encoded webp image the serializer throw a `ValidationError` with saying: "The type of the image couldn't be determined."

## Expected behavior

Upload webp image success

**Comment by ksenia790** [comment]
Format webp still not allowed(
