### ISSUE TITLE
Compatibility with psycopg package (psycopg3)

### ISSUE THREAD

**Issue by james-certn** [Hipo/drf-extra-fields#190]
Is it possible to add support for psycopg(3)? I don't know this codebase well, but [this line](https://github.com/Hipo/drf-extra-fields/blob/master/drf_extra_fields/fields.py#L27) appears to be that which enables psycopg2 support.

With [Django moving to support psycopg(3)](https://docs.djangoproject.com/en/4.2/releases/4.2/#psycopg-3-support), it's going to soon become a need for this package.

**Comment by hartungstenio** [comment]
Hello. I'm opening a draft for this: See #202 .

Just working on a few compatibility issues.

**Comment by KaratasFurkan** [comment]
It's now supported in version `3.7.0` thanks to @hartungstenio, you can download it from `pip`.
