### ISSUE TITLE
Publish a release for each PyPI release

### ISSUE THREAD

**Issue by benf-wspdigital** [Hipo/drf-extra-fields#24]
Related to issue #9, the [GitHub releases page](https://github.com/Hipo/drf-extra-fields/releases) shows only “v0.1” and “v0.3”.

Please make a release at GitHub for each release published to PyPI (and vice versa also).

**Comment by benf-wspdigital** [comment]
Ideally this should be part of the release procedure every time: tag the release; publish the release files at GitHub; publish the release files at PyPI.

**Comment by alicertel** [comment]
@benf-wspdigital Thank you for suggestion. We are creating a github release for each PyPI release.
