### ISSUE TITLE
Declare more PyPI metadata

### ISSUE THREAD

**Issue by benf-wspdigital** [Hipo/drf-extra-fields#26]
Some of the important information for the package are missing from the PyPI metadata.

Please add the following in the PyPI metadata:
- Project homepage (`url`)
- Maintainer name (`maintainer`) and email address (`maintainer_email`)
- License grant (`license`)
- Trove classifier for license (in `classifiers`, the “License :: …” entry)

**Comment by yigitguler** [comment]
Thank you, we will try to add as soon as possible.

**Comment by johnthagen** [comment]
What versions of Django / DRF are supported? We should probably have a matrix of tested versions similar to this: https://github.com/axnsan12/drf-yasg/blob/master/tox.ini#L7

**Comment by dynamodeniz** [comment]
Any progress on this? It would help our current project immensely to have up-to-date metadata information, at least the license, in PyPI, because we are automatically generating a list of all the 3rd party Python libraries that we are using including their license.

**Comment by alicertel** [comment]
@dynamodeniz it's updated last week. Here is the made changes. https://github.com/Hipo/drf-extra-fields/pull/71/files 

We will make a new release soon. Please let me know if you think something is missing.

**Comment by dynamodeniz** [comment]
@alicertel Awesome! 👍 Thanks!

If you want to be extra helpful, maybe you could add `home_page` (linking to this GitHub for example) but a license is enough for my needs :)

**Comment by alicertel** [comment]
@dynamodeniz Thank you. I will add home_page too before the new release.

**Comment by alicertel** [comment]
This is completed.
