### ISSUE TITLE
If defined a PointField on my model. Do I need to define it on the serializer too?

### ISSUE THREAD

**Issue by JoabMendes** [Hipo/drf-extra-fields#29]
I have a field written like than on my model

```python
from django.contrib.gis.db import models
...
location = models.PointField(null=True, blank=True, srid=GOOGLE_MAPS_SRID)
...
```

Do I need to define it again on this model serializer or the `fields = '__all__'` will identify it already?

**Comment by yigitguler** [comment]
Hello,

Yes, you should add a line to the modelserializer as well.

`    location = PointField()
`

**Comment by JoabMendes** [comment]
Alright. Thank you @yigitguler
