### ISSUE TITLE
Base64ImageField saved as "Raw content" on PUT requests

### ISSUE THREAD

**Issue by xtrinch** [Hipo/drf-extra-fields#30]
Note: I am using Django==1.9.8 and djangorestframework==3.2.4.
Everything works as expected on POST and GET requests, but on PUT requests - no image is generated in my filesystem and where the file URL should be, there's a "Raw content" string.

**Comment by yigitguler** [comment]
Hello @xtrinch,

In order to help you, I need some extra information. Can you send me the example request of the PUT request? This will help a lot.

Best

Yigit

**Comment by xtrinch** [comment]
I have tracked the error down to the update method on a queryset - example:

```
businesses = Business.objects.filter(id=business.id)
businesses.update(**business_data)
```

If I manually assign it the following way, it works:

`business.photo = business_data['photo']`

This probably couldn't be classified as a bug?

**Comment by yigitguler** [comment]
Yeah, that is an expected result. Marking as closed.
