### ISSUE TITLE
Using header in get_file_extension

### ISSUE THREAD

**Issue by shubhamjain0594** [Hipo/drf-extra-fields#39]
Why header is not used to get_file_extension. It can be passed as a parameter to get file extension.

**Comment by yigitguler** [comment]
Hi,

I am not sure I understand your comment. Could you please elaborate?

Thank you.

**Comment by shubhamjain0594** [comment]
Sorry for not being elaborate.

```python
# Strip base64 header.
if ';base64,' in base64_data:
        header, base64_data = base64_data.split(';base64,')
```

Here we extract header from the base64encoding.

```python
file_extension = self.get_file_extension(file_name, decoded_file)
```

header once extracted is not used anywhere. In cases when file type can be multiple types. Header can be used to extract the type in cases the file is not an image. 

We can modify get_file_extension so that even header is passed as an argument.

**Comment by shubhamjain0594** [comment]
If you approve I can send a PR for this.

**Comment by yigitguler** [comment]
As far as I understand, you are proposing to store file_extension to self.file_extension and access this in future. I think it will be easier to understand if you just open a PR :)

**Comment by shubhamjain0594** [comment]
Created PR [here](https://github.com/Hipo/drf-extra-fields/pull/40)

**Comment by alicertel** [comment]
Closed with https://github.com/Hipo/drf-extra-fields/pull/40
