### ISSUE TITLE
Browsable API crashes with PresentablePrimaryKeyRelatedField

### ISSUE THREAD

**Issue by scheparev-moberries** [Hipo/drf-extra-fields#43]
While declaring the presentable primary key related field like following:

```
city = PresentablePrimaryKeyRelatedField(
        queryset=City.objects,
        presentation_serializer=CitySerializer
    )
```

where city serializer is

```
class CitySerializer(ModelSerializer):
    class Meta:
        model = City
```

I get `unhashable type: 'ReturnDict'` in the browsable API. Any ideas how to fix it?

**Comment by scheparev-moberries** [comment]
Looks like `get_choices` fails to build an OrderedDict with key from representation.
Workaround monkeypatch get_choices like following:

```
    def get_choices(self, cutoff=None):
        queryset = self.get_queryset()
        if queryset is None:
            # Ensure that field.choices returns something sensible
            # even when accessed with a read-only field.
            return {}

        if cutoff is not None:
            queryset = queryset[:cutoff]

        return OrderedDict([
            (
                item.pk,
                self.display_value(item)
            )
            for item in queryset
        ])

```

**Comment by yigitguler** [comment]
Hi @scheparev-moberries,

Thank you for the report. @alicertel is responsible from that field. Assigning to him.

**Comment by scheparev-moberries** [comment]
@safwanrahman checked, it's working, thanks!

**Comment by changming1987117** [comment]
I have met this problem again
Django == 1.10
djangorestframework == 3.4.6
django-extra-fields == 0.9
@scheparev-moberries ,could you tell me how to resolve it?
thx

**Comment by yigitguler** [comment]
We took a release (0.10) you can use it from pypi as well.
