### ISSUE TITLE
Rename the pypi package to `drf-extra-fields`

### ISSUE THREAD

**Issue by mlorant** [Hipo/drf-extra-fields#54]
Today, this github project is named "drf-extra-fields", which is good, since it is hosting fields for the Django REST Framework.

However, the PyPi package is `django-extra-fields` which creates confusion, and is incorrect since the package does not "add" fields for Django itself. 

Maybe this was for SEO reasons (easier to find the package with the keyword django in it), but this can be resolved with metadata info on the package :)

**Comment by ulgens** [comment]
@yigitguler @alicertel Ping? :slightly_smiling_face:

**Comment by yigitguler** [comment]
I believe this is because of a simple mistake rather than an SEO effort :)

We will change the name when we will be able to allocate time.

**Comment by ulgens** [comment]
As a solution for that, we discussed about uploading another package with correct name but also keep supporting the old one for a reasonable time (~1 year). I looked for how `psycopg2` did this in past, found this: https://github.com/psycopg/psycopg2-wheels/commit/cf03a558 I'm not sure how we can adopt this, but i think it a start at least.

**Comment by johnthagen** [comment]
@alicertel Would this be possible for the next release?

**Comment by alicertel** [comment]
New package released as [drf-extra-fields](https://pypi.org/project/drf-extra-fields/3.0.2/). From now on you can install the new versions via `pip install drf-extra-fields`.
