### ISSUE TITLE
Couldn't determine file format when used base64 for image upload

### ISSUE THREAD

**Issue by joshi-ameya** [Hipo/drf-extra-fields#57]
Hello, I am new to this package, so please tell me if I am in right direction to implement this or not.

So I have integrated this package in my current project, I am implementing a simple image upload flow.

My user model is,
`
       ```
class User(models.Model):
             image = models.ImageField(required=False)
```
`
and my model serializer is ,
`
     ```
 from drf_extra_fields.fields import Base64ImageField
      from .models import User
      class UserSerializer(serializers.ModelSerializer):
           image = Base64ImageField(required=False)
        
            class Meta:
                 model = User
```
`

Now, from frontend I am sending image in base64 format, 
```
`
    {
        'image': 'data:image/jpeg;base64,/9 ......'
    }
`
```
 **But I am getting type error message,  'The type of the image couldn't be determined.'**
I have looked into code in _fields.py_, and I see the part causing me problem is 
`
 ```
class Base64FieldMixin(object):
      .....       
      def to_internal_value(self, base64_data):
            .....
            if isinstance(base64_data, six.string_types):
                 .........
                 if ';base64,' in base64_data:                                                                                                 
                       header, base64_data = base64_data.split(';base64,')
                 ......... 
                 # generate file_name
                  file_name = str(uuid.uuid4())[:12]  # 12 characters are more than enough.                                                     
                  # Get the file name extension:                                                                                                
                  _file_extension = self.get_file_extension(file_name, decoded_file)_ 
         
  class Base64ImageField(Base64FieldMixin, ImageField):
     .......
     def get_file_extension(self, filename, decoded_file):                                                                                
           extension = imghdr.what(filename, decoded_file)                                                                                  
           extension = "jpg" if extension == "jpeg" else extension                                                                          
           return extension
`
```
To my understanding this code is sending the new encoded file name to get extension which doesn't have any relation to extension. Thats why I get _None_  returned as _file_extension_
But if I replace that code simply with
```
`
      file_extension= header.split('/')[1]
`
```
and this works fine.

So actually I am confused which side is wrong in this scenario, frontend or backend code of this package? Am I sending the wrong base64 format , or is there something I didn't understand about current logic you guys have implemented. 
Please guide me.  And , honestly thank you for reading this big explanation.

**Comment by kelly-ry4n** [comment]
If you just want to fix this client side, you can use javascript to write the image to a canvas and reencode it as a base64 image.

```javascript

// e is the event from a <input type="file" /> onchange

const file = e.target.files[0]; 
rewriteAsJpgAndSubmit(file)

rewriteAsJpgAndSubmit = (file) => {

    const reader = new FileReader()

    reader.onloadend = (e) => {


        const img = new Image()
        img.src = "" // onload event sometimes won't fire in webkit without this


        img.onload = (e) => {

            const canvas = document.createElement('canvas')

            canvas.width = img.width
            canvas.height = img.height

            const ctx = canvas.getContext('2d')
            ctx.drawImage(img, 0, 0, width, height)

            const dataUrl = canvas.toDataURL('image/jpeg', 90) // 90 is the jpg compression quality

            // dataUrl contains the (fixed) URL to submit to the Base64ImageField. Do something with it here.

        }

	    img.src = reader.result
	}
}
```

This fixes the error for me.

**Comment by Luca1991** [comment]
I just encountered this issue in my project. 
I'd like to add that if I use PNG images, this bug is not triggered. 
This happens only with JPEG images as far as I can see.

**Comment by alicertel** [comment]
@Luca1991 Thank you for your feedback. I will have a look at this issue early next week. Can you please send the base64 text which is failed?

**Comment by Luca1991** [comment]
Hi @alicertel thank you for reading my post. From what I can see after running some tests, some jpeg actually works, but not all.
Here is the base64 of a problematic jpeg (it is part of my avatar here on github): https://pastebin.com/ms4ZqinU

Let me know if I can help you in some way ;)

**Comment by alicertel** [comment]
@Luca1991 thank you for details. Looks like there is [bug](https://bugs.python.org/issue16512) in imghdr method. There is an active PR https://github.com/Hipo/drf-extra-fields/pull/75 related with this issue. I will let you know when it's merged and a new version is released.

**Comment by Luca1991** [comment]
Perfect :+1:  Thank you very much for your time :smile:

**Comment by alicertel** [comment]
This issue is resolved and new version is released. 

@nafeesanwar Thank you so much for your contribution.
