### ISSUE TITLE
NameError: name 'basestring' is not defined (python3.5)

### ISSUE THREAD

**Issue by linpan** [Hipo/drf-extra-fields#58]
value = self.to_internal_value(data)
  File "/home/user/env/lib/python3.5/site-packages/drf_extra_fields/fields.py", line 31, in to_internal_value
    if isinstance(base64_data, basestring):
NameError: name 'basestring' is not defined

**Comment by alicertel** [comment]
@linpan Looks like you are not upto date. Can you please update your package to the latest version? 

There is only one breaking change which is easy to fix.  Please [refer](https://github.com/Hipo/drf-extra-fields#releases) to the documentation.

**Comment by ryan28561** [comment]
I just ran into the same issue on version 0.3 which is listed in the documentation as the current version for dry 3.*. If there's a more recent version, I would appreciate it if the documentation was updated.
