### ISSUE TITLE
REST Framework 3.9.0 breaks tests

### ISSUE THREAD

**Issue by onlined** [Hipo/drf-extra-fields#64]
https://github.com/Hipo/drf-extra-fields/blob/8c79bdc82a590402d7435996abfa90fd56cd85c7/tests/test_fields.py#L554-L556

The test expecting this output fails because the date format in the exception text was changed in DRF 3.9.0 from `YYYY[-MM[-DD]]` to `YYYY-MM-DD`.

**Comment by alicertel** [comment]
Fixed with https://github.com/Hipo/drf-extra-fields/pull/68

**Comment by onlined** [comment]
Thanks!
