### ISSUE TITLE
Base64VideoField?

### ISSUE THREAD

**Issue by elcolie** [Hipo/drf-extra-fields#81]
Hi. Thanks to your wonderful library. I can upload `base64Image` file to my system.
I am finding workaround on `video`. Do you have any idea on [this](https://stackoverflow.com/questions/55779866/implement-base64videofield-django-rest?noredirect=1#comment98231232_55779866)?

**Comment by yigitguler** [comment]
Hi,

Just use [Base64FileField](https://github.com/Hipo/drf-extra-fields#base64filefield) and set ALLOWED_TYPES with popular video types like mpg, mp4, etc...
