### ISSUE TITLE
New Field Propose: LowercaseEmailField

### ISSUE THREAD

**Issue by efe** [Hipo/drf-extra-fields#89]
`EmailField` of Django REST Framwork is case-sensitive. Because, It follows the email specification [RFC2882](https://tools.ietf.org/html/rfc2822). However, Most of email providers follow case-insensitive approach.

So, I'd like to have `LowercaseEmailField` for this package.

```python
from rest_framework.fields import EmailField

class LowercaseEmailField(EmailField):

    def __init__(self, **kwargs):
        super(LowercaseEmailField, self).__init__(**kwargs)

    def to_internal_value(self, data):
        data = super().to_internal_value(data)
        return data.lower()

    def to_representation(self, value):
        value = super().to_representation(value)
        return value.lower()
```

**Comment by alicertel** [comment]
Sounds like a good addition. What do you think @yigitguler ?

**Comment by yigitguler** [comment]
I agree!

**Comment by alicertel** [comment]
@efe Expecting a PR then :)

FYI: You don't need to override `__init__`

**Comment by efe** [comment]
Thanks!
