### ISSUE TITLE
Make PIL optional

### ISSUE THREAD

**Issue by nitely** [Hipo/drf-extra-fields#91]
It seems a hard dependency to PIL [was added recently](https://github.com/Hipo/drf-extra-fields/commit/c6a05d6a6750e9dd894a6a598c1d8200e012feea) but not every field requires PIL and not all projects require PIL either. I think this requirement should be optional. Otherwise, we are forced to install the [PIL pre-requirements](https://pillow.readthedocs.io/en/stable/installation.html#building-on-macos).

**Comment by alicertel** [comment]
@nitely Thanks for contribution. It's been merged to master. We will take a new release early next week.

**Comment by ulgens** [comment]
This issue is resolved by https://github.com/Hipo/drf-extra-fields/pull/93 and i think it can be closed.
