### ISSUE TITLE
setup.py is missing the requirements

### ISSUE THREAD

**Issue by nitely** [Hipo/drf-extra-fields#92]
I think this was always an issue, but since most projects using this library already have django and drf installed nobody has noticed it. Except now pillow was added. I propose breaking the requirement file into requirements.txt and requirements-dev.txt and add the former to setup.py. Either that or hard-code the requirements into setup.py.

**Comment by alicertel** [comment]
Thank you @nitely We will also add Pillow as optional requirements.
