### ISSUE TITLE
Auto file name generated by uuid4 can be blocked by adblockers

### ISSUE THREAD

**Issue by maratumba** [Hipo/drf-extra-fields#94]
Random names generated by drf-extra-fields include file names that end with `-ad0`, which is blocked by ublock origin and possibly other adblockers. Will create a pull request to increase the string length by 1 to avoid this issue.

See this [issue by me](https://stackoverflow.com/questions/57227131/images-that-fit-the-regexp-ad0-9-png-can-not-be-loaded-in-any-browser/57227395#57227395) on stackoverflow
https://github.com/Hipo/drf-extra-fields/blob/e33048bdba6e82ba3f61719466b73d50f8a695e2/drf_extra_fields/fields.py#L83

**Comment by alicertel** [comment]
@maratumba Thank you for your contribution. This is resolved.
